# Generated by Django 4.0.1 on 2022-10-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPAdministrarTareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreE', models.CharField(max_length=30)),
                ('apellidoE', models.CharField(max_length=30)),
                ('correoE', models.EmailField(max_length=254)),
                ('celularE', models.CharField(max_length=10)),
                ('cedulaE', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=15)),
                ('contra', models.CharField(max_length=15)),
                ('carrera_E', models.CharField(choices=[('sistemas', 'sistemas'), ('computacion', 'computacion'), ('electricidad', 'electricidad'), ('electronica', 'electronica')], default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreM', models.CharField(max_length=30)),
                ('nroHoras', models.PositiveSmallIntegerField()),
                ('nombreProfesor', models.CharField(max_length=30)),
                ('nroCreditos', models.PositiveSmallIntegerField()),
                ('cadena_M', models.CharField(choices=[('no', 'no'), ('si', 'si')], default='', max_length=30)),
                ('ciclo_M', models.CharField(choices=[('1ero', '1ro'), ('2do', '2do'), ('3ro', '3ro'), ('4to', '4to'), ('5to', '5to'), ('6to', '6to'), ('7mo', '7mo'), ('8vo', '8vo')], default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=30)),
                ('apellidoP', models.CharField(max_length=30)),
                ('correoP', models.EmailField(max_length=254)),
                ('celularP', models.CharField(max_length=10)),
                ('cedulaP', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=15)),
                ('contra', models.CharField(max_length=15)),
                ('carrera_P', models.CharField(choices=[('sistemas', 'sistemas'), ('computacion', 'computacion'), ('electricidad', 'electricidad'), ('electronica', 'electronica')], default='', max_length=30)),
            ],
        ),
    ]
