# Generated by Django 4.0.1 on 2022-10-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPAdministrarTareas', '0002_estudiante_materia_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=15)),
                ('contra', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='contra',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='contra',
        ),
    ]
