# Generated by Django 4.0.1 on 2022-10-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPAdministrarTareas', '0003_persona_remove_estudiante_contra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreContacto', models.CharField(max_length=30)),
                ('apellidoContacto', models.CharField(max_length=30)),
                ('correoContacto', models.EmailField(max_length=254)),
            ],
        ),
    ]
