# Generated by Django 4.0.1 on 2022-10-27 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPAdministrarTareas', '0004_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarreraUniversitaria',
            fields=[
                ('codigoCarrera', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombreCarrera', models.CharField(max_length=30)),
                ('duracionCarrera', models.PositiveSmallIntegerField(default=8)),
                ('descripcionCarrera', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='CursoUniversidad',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('docente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteCarrera',
            fields=[
                ('cedula', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('apellidoPaterno', models.CharField(max_length=30)),
                ('apellidoMaterno', models.CharField(max_length=30)),
                ('nombresEstudiante', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'F'), ('M', 'M')], default='F', max_length=1)),
                ('vigenciaEstudiante', models.BooleanField(default=True)),
                ('carreraUniversitaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPAdministrarTareas.carrerauniversitaria')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('idMatricula', models.AutoField(primary_key=True, serialize=False)),
                ('fechaMatricula', models.DateTimeField(auto_now_add=True)),
                ('cursoUniversidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPAdministrarTareas.cursouniversidad')),
                ('estudianteCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPAdministrarTareas.estudiantecarrera')),
            ],
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
