# Generated by Django 4.0.1 on 2022-10-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPAdministrarTareas', '0005_carrerauniversitaria_cursouniversidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantecarrera',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
